var formMsg={
    usernamePatrn : /^([a-zA-Z0-9]){6,20}$/,  	
	usernameNullMsg: "用户名不能为空！",
	usernameErrMsg: "您的用户名输入有误，请输入6-16位字母或数字！",
	userpwdPatrn  : /^([a-zA-Z0-9]){6,20}$/, 
	userpwdNullMsg:  "用户密码不能为空！",
	userpwdErrMsg:   "您的密码输入有误，请输入6-16位字母或数字！",
	userpwdnew:      "请输入新密码！",
	userpwdconfirm:  "请输入确认密码！",
    useryzmErrMsg:   "您两次输入的密码不一致!",
	truenamePatrn:   /^([\u4e00-\u9fa5 ]){2,6}$/,
	truenameNullMsg: "用户真实姓名不能为空！",
	truenameErrMsg:  "您的真实姓名输入有误！",
	phonePatrn:      /^((\d){3,4}(-){0,1}(\d){7,8}(-){0,1}(\d){0,4}([ |,;]){0,2}){0,2}$/,
	phonecurrency:   /^([\d]{3,4}(-){0,1}[\d]{7,11}(-){0,1}[\d]{0,4}[ |,;]{0,1}){0,2}$/,
	phoneNullMsg:    "您的联系电话不能为空！",
	phoneErrMsg:     "您输入的联系电话有误，请输入一个固定电话(区号-座机号)！多号码请以,或|号分隔。",
    phoneErrcurrency: "您填写的联系电话有误，填写您固定电话(区号-座机号)或者手机号码！",
	faxPatrn:        /^(\d){3,4}(-){0,1}(\d){6,8}(-){0,1}(\d)*$/,
	faxMsg:          "传真格式错误，区号以及转播号间请哟个'-'好连接。",
	mobilePatrn:     /^([0]{0,1}(13||15|18){1}(\d){1}[-]?(\d){8}([ ,;]){0,2}){0,2}$/,
	mobileError:     "请正确填写手机号码",
	//mobilePatrncurrency :/^((0){0,1}(\d){11}[,;]{0,1}){0,2}$/,
	emailPatrn:      /^([a-z.A-Z0-9_-])+(@)([a-zA-Z0-9_-])+([.a-zA-Z0-9_-])+(\.){1}(com|cn|net|org|COM|CN|NET|ORG){1}$/,
	emailNullMsg:    "电子邮箱不能为空！",
	emailErrMsg:     "您的电子邮箱输入有误！当您忘记密码时可用电子邮箱取回密码，请正确填写！",
	emailErr1Msg:     "您的电子邮箱输入有误！请正确填写！",
	companyNullMsg:  "公司名称不能为空！",
	companyErrMsg:   "您输入的公司名称有误！",
	companyNameErr:  "请输入公司全称！",
	companyNameErrmax:"您输入的公司名称太长，请填写合适的公司名称！",
	companyaddrNullMsg:  "公司地址不能为空！",
	companyaddrErrMsg:  "您输入的公司地址有误！",
	yzmNullMsg:      "请输入验证码",
	phonemobilenull: "用户联系电话和手机号码不能同时为空！",
	onlyphoneErr:    "您输入的固定电话有误！",
	onlymobileErr:   "您输入的手机号码有误！",
	qqMsnPatrn:      /^[\d]*$/,
	qqMsnMsg:        "QQ以及MSN请填写数字！",
	priceFloat:     /^[1-9][\d]*(.){0,1}[\d]{0,2}$/,
	priceFloatMsg:   "价格输入错误，首位不能为0，小数点后保留2位有效数字。",
	httpPatern:      /http:\/\//,
	httpMsg:         "请输入正确的网址,以http://开头。",
	postCodePatern:  /^[\d]{6}$/,
	postCodeMsg:     "邮政编码有误，请正确填写。"
}

var opMsg={
	succsubmit:"提交成功",
	succedit:"修改成功",
	succupload:"上传成功",
	succpass:"审核成功",
	succkeepOp:"续期成功",
	failsubmit:"提交失败",
	failedit:"修改失败",
	failupload:"上传失败",
	failpass:'审核失败',
	failkeepOp:"续期失败"
};